import { WindowIpc } from "./windowIpc.type";
import { DialogIpc } from "./dialogIpc.type";
import { FsIpc } from "./fsIpc.type";
import { DownloadIpc } from "./downloadIpc.type";
import { CryptoIpc } from "./cryptoIpc.type";
import { AppIpc } from "./app.type";
import { ILog } from "./logIpc.type";
import { Ipath } from "./path.type";
import { SqlIpc } from "./sql.type";
import { InetWorkIpc } from "./network.type";
import { ICoapIpc } from "./coap.type";
import { IcanIpc } from "./can.type";
import { IgrpcIpc } from "./grpc.type";
import { SSHIpc } from "./sshipc.type";
import { SftpIpc } from "./sftpipc.type";
import { IHdcIpc } from "./hdc.type";
import { IOrm } from "./orm.type";
import { IjfrogClient } from "./jfrogClient.type";
import { IBlueIpc } from "./blue.type";
import { ISerialportIpc } from "./serialport.type";
import { ISimulatorIpc } from "./simulator.type";
import { IGitIpc } from "./git.type";
import { IscpClient } from "./scp.type";
import { INatsClient } from "./nats.type";
import { BufferIpc } from "./bufferIpc.type";
import { MqttIpc } from "./mqtt.type";
import { IProcessIpc } from "./process.type";
import { ICoap2Ipc } from "./coap2.type";

export type IApi = {
  app: AppIpc;
  wind: WindowIpc;
  dialog: DialogIpc;
  download: DownloadIpc;
  buffer: BufferIpc;
  fs: FsIpc;
  path: Ipath;
  sql: SqlIpc;
  log: ILog;
  orm: IOrm;
  crypto: CryptoIpc;
  netWork: InetWorkIpc;
  coap: ICoapIpc;
  coap2: ICoap2Ipc;
  can: IcanIpc;
  grpc: IgrpcIpc;
  ssh: SSHIpc;
  sftp: SftpIpc;
  hdc: IHdcIpc;
  jfrog: IjfrogClient;
  blue: IBlueIpc;
  serialport: ISerialportIpc;
  simulator: ISimulatorIpc;
  git: IGitIpc;
  scp: IscpClient;
  nats: INatsClient;
  mqtt: MqttIpc;
  process: IProcessIpc;
};
